import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { ArrowRight, Check, CircleGauge, Dumbbell, MoonStar } from "lucide-react";
import { Button } from "@/components/ui/button";
import { DemoBadge, DemoNotice, PageIntro, Segmented } from "@/components/sports-ui";
import { recommendations } from "@/lib/sports-data";
export const Route=createFileRoute("/recommendations")({head:()=>({meta:[{title:"Performance Recommendations — SportsMax"},{name:"description",content:"Explore personalized demo recommendations based on athlete performance analytics and recent training patterns."},{property:"og:title",content:"Personalized Recommendations — SportsMax"},{property:"og:description",content:"Analytics-based next steps for recovery, endurance, and consistency."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:"/recommendations"}]}),component:Recommendations});
const icons=[MoonStar,Dumbbell,CircleGauge];
function Recommendations(){const [filter,setFilter]=useState("All");const [saved,setSaved]=useState<number[]>([]);const shown=filter==="All"?recommendations:recommendations.filter(r=>r.type===filter);return <><PageIntro eyebrow="Actionable intelligence" title="Personalized Performance Recommendations" text="Demo analytics translate recent training signals into focused next steps you can review with your coach." action={<DemoBadge/>}/><section className="py-12"><div className="content-wrap"><div className="mb-6 flex flex-wrap items-center justify-between gap-4"><Segmented values={["All","Recovery","Endurance","Consistency"]} value={filter} onChange={setFilter}/><span className="text-xs text-muted-foreground">Based on the latest 28 sessions</span></div><div className="grid gap-4 lg:grid-cols-3">{shown.map((r)=>{const actualIndex=recommendations.indexOf(r);const Icon=icons[actualIndex] ?? CircleGauge;const isSaved=saved.includes(actualIndex);return <article key={r.number} className="surface-card flex min-h-96 flex-col p-6"><div className="flex items-start justify-between"><span className="font-mono text-xs text-muted-foreground">REC / {r.number}</span><span className="rounded border border-primary/25 bg-primary/10 px-2 py-1 text-[11px] font-semibold text-primary">{r.priority}</span></div><Icon className="mt-8 h-9 w-9 text-accent"/><p className="mt-6 text-xs font-bold uppercase tracking-widest text-primary">{r.type}</p><h2 className="mt-2 text-2xl font-semibold">{r.title}</h2><p className="mt-3 flex-1 text-sm leading-6 text-muted-foreground">{r.detail}</p><div className="mt-6 border-t border-border pt-4"><p className="text-xs text-muted-foreground">Supporting signal</p><p className="mt-1 font-mono text-sm">{r.evidence}</p><Button onClick={()=>setSaved(isSaved?saved.filter(i=>i!==actualIndex):[...saved,actualIndex])} variant={isSaved?"secondary":"outline"} className="mt-4 w-full">{isSaved?<><Check/>Added to plan</>:<>Review action<ArrowRight/></>}</Button></div></article>})}</div><div className="mt-6"><DemoNotice/></div></div></section></>}
