export interface SportItem {
  id: string;
  name: string;
  category: "individual" | "team" | "analysis";
  subcategory?: string;
  href: string;
  description: string;
  iconName: string;
  badge?: string;
  metrics: string[];
  primaryStat: { label: string; value: string; trend: string };
  athletesTracked: string;
  featured?: boolean;
}

export const INDIVIDUAL_SPORTS: SportItem[] = [
  {
    id: "running",
    name: "Running",
    category: "individual",
    subcategory: "Endurance & Speed",
    href: "/sports/running",
    description: "GPS tracking, cadence analytics, VO2 max estimation, split pacing, and elevation metrics.",
    iconName: "Flame",
    badge: "Flagship",
    metrics: ["Pace (min/km)", "Cadence (spm)", "Heart Rate Zones", "Elevation Gain", "Split Times"],
    primaryStat: { label: "Avg Pace", value: "5:18 /km", trend: "+6.0% faster" },
    athletesTracked: "14,250+",
    featured: true,
  },
  {
    id: "swimming",
    name: "Swimming",
    category: "individual",
    subcategory: "Aquatics",
    href: "/sports/swimming",
    description: "Stroke count, SWOLF efficiency index, turn velocity, underwater kick phase, and lap-by-lap splits.",
    iconName: "Waves",
    badge: "Popular",
    metrics: ["SWOLF Score", "Stroke Rate", "Turn Time", "Underwater Phase", "Heart Rate"],
    primaryStat: { label: "SWOLF Score", value: "32.4", trend: "Top 5% efficiency" },
    athletesTracked: "6,840+",
    featured: true,
  },
  {
    id: "high-jump",
    name: "High Jump",
    category: "individual",
    subcategory: "Athletics & Track",
    href: "/sports/athletics/high-jump",
    description: "Approach curve speed, takeoff vertical velocity, Fosbury bar clearance height, and center-of-mass trajectory.",
    iconName: "ArrowUpRight",
    badge: "Field Event",
    metrics: ["Approach Speed", "Takeoff Angle", "Vertical Velocity", "Bar Clearance Margin", "Plant Foot Force"],
    primaryStat: { label: "Clearance PB", value: "2.28 m", trend: "+4 cm this season" },
    athletesTracked: "1,920+",
    featured: true,
  },
  {
    id: "sprints",
    name: "Sprints (100m - 400m)",
    category: "individual",
    subcategory: "Athletics & Track",
    href: "/sports/athletics/high-jump",
    description: "Block clearance reaction time, 0-30m acceleration phase, max velocity maintenance, and stride frequency.",
    iconName: "Zap",
    metrics: ["Block Reaction", "0-30m Split", "Top Velocity (m/s)", "Stride Length", "Deceleration Index"],
    primaryStat: { label: "100m Split", value: "10.14 s", trend: "0.12s block reaction" },
    athletesTracked: "5,410+",
  },
  {
    id: "distance-events",
    name: "Distance Events (5K - Marathon)",
    category: "individual",
    subcategory: "Athletics & Track",
    href: "/sports/running",
    description: "Lactate threshold modeling, sustained aerobic output, carbohydrate burn rates, and pacing strategy.",
    iconName: "Milestone",
    metrics: ["Aerobic Threshold", "Hydration Loss", "Negative Splits", "Cadence Drift", "Fatigue Resistance"],
    primaryStat: { label: "Half Marathon", value: "1:14:22", trend: "Negative split -42s" },
    athletesTracked: "9,120+",
  },
  {
    id: "jumps-throws",
    name: "Jumps & Throws",
    category: "individual",
    subcategory: "Athletics & Track",
    href: "/sports/athletics/high-jump",
    description: "Kinematic release angles in shotput, javelin, and discus; long jump approach speed and board precision.",
    iconName: "Crosshair",
    metrics: ["Release Velocity", "Angle of Release", "Approach Speed", "Foul Board Margin", "Torque Vector"],
    primaryStat: { label: "Long Jump PB", value: "8.12 m", trend: "Wind legal +1.2 m/s" },
    athletesTracked: "2,380+",
  },
  {
    id: "cycling",
    name: "Cycling",
    category: "individual",
    subcategory: "Endurance & Speed",
    href: "/sports/running",
    description: "Normalized power (NP), Functional Threshold Power (FTP), pedaling torque effectiveness, and cadence smoothing.",
    iconName: "Compass",
    metrics: ["FTP (Watts)", "W/kg Ratio", "Cadence (rpm)", "Aerodynamic Drag (CdA)", "Elevation Profile"],
    primaryStat: { label: "FTP Output", value: "345 W", trend: "4.8 W/kg" },
    athletesTracked: "8,900+",
  },
  {
    id: "tennis",
    name: "Tennis & Racket Sports",
    category: "individual",
    subcategory: "Precision & Agility",
    href: "/sports/football",
    description: "Serve speed, rally shot placement depth, spin RPM, court coverage heatmaps, and unforced error tracking.",
    iconName: "Target",
    metrics: ["Serve Speed (km/h)", "Spin Rate (RPM)", "Court Coverage (m)", "1st Serve In %", "Break Point Conv."],
    primaryStat: { label: "1st Serve Avg", value: "198 km/h", trend: "72% In-rate" },
    athletesTracked: "4,620+",
  },
  {
    id: "golf",
    name: "Golf",
    category: "individual",
    subcategory: "Precision",
    href: "/sports/athletics/high-jump",
    description: "Clubhead speed, launch angle, smash factor, apex trajectory, spin rate, and strokes gained metrics.",
    iconName: "Flag",
    metrics: ["Clubhead Speed", "Smash Factor", "Launch Angle", "Ball Spin (RPM)", "Strokes Gained"],
    primaryStat: { label: "Driver Carry", value: "294 yds", trend: "Smash factor 1.49" },
    athletesTracked: "3,750+",
  },
  {
    id: "combat-sports",
    name: "Combat Sports (Boxing / MMA / Judo)",
    category: "individual",
    subcategory: "Power & Reaction",
    href: "/sports/athletics/high-jump",
    description: "Strike impact velocity, strike accuracy %, takedown defense %, reaction latency, and cardiovascular output.",
    iconName: "Shield",
    metrics: ["Strike Velocity", "Impact Force (G)", "Reaction Time (ms)", "Significant Strikes %", "Heart Recovery"],
    primaryStat: { label: "Reaction Time", value: "182 ms", trend: "Sub-200ms elite tier" },
    athletesTracked: "2,190+",
  },
];

export const TEAM_SPORTS: SportItem[] = [
  {
    id: "football",
    name: "Football / Soccer",
    category: "team",
    subcategory: "Field Team Sport",
    href: "/sports/football",
    description: "Expected Goals (xG), pitch control heatmaps, pressing intensity (PPDA), pass completion clusters, and high-speed running distance.",
    iconName: "Goal",
    badge: "Flagship",
    metrics: ["Expected Goals (xG)", "PPDA Pressing", "Pass Matrix %", "High-Speed Sprints", "Defensive Line Height"],
    primaryStat: { label: "xG Created", value: "2.48", trend: "+0.62 vs opponent" },
    athletesTracked: "18,400+",
    featured: true,
  },
  {
    id: "hockey",
    name: "Hockey (Ice & Field)",
    category: "team",
    subcategory: "Puck & Stick",
    href: "/sports/hockey",
    description: "Shift length optimization, zone entry transition speed, puck possession %, turnover recovery, and shot suppression.",
    iconName: "ShieldAlert",
    badge: "Popular",
    metrics: ["Corsi %", "Shift Duration", "Zone Entries", "Faceoff Win %", "Puck Possession (min)"],
    primaryStat: { label: "Corsi For %", value: "58.4%", trend: "Elite control tier" },
    athletesTracked: "7,310+",
    featured: true,
  },
  {
    id: "relay",
    name: "Relay & Combined Events",
    category: "team",
    subcategory: "Track & Multi-Discipline",
    href: "/sports/relay",
    description: "Baton exchange box speed differentials, 20m acceleration zone splits, decathlon/heptathlon point curves.",
    iconName: "Shuffle",
    badge: "Track & Field",
    metrics: ["Baton Transfer Delta", "Exchange Speed (m/s)", "Split Pacing", "Point Aggregation", "Foul Margin"],
    primaryStat: { label: "4x100m Exchange", value: "1.74 s", trend: "0.18s faster than average" },
    athletesTracked: "3,140+",
    featured: true,
  },
  {
    id: "basketball",
    name: "Basketball",
    category: "team",
    subcategory: "Court Team Sport",
    href: "/sports/football",
    description: "True Shooting % (TS%), defensive rating, pace-adjusted offensive rating, shot chart heatmaps, and pick-and-roll efficiency.",
    iconName: "CircleDot",
    metrics: ["True Shooting %", "Net Rating", "Rebound %", "Assist-to-Turnover", "Pace Factor"],
    primaryStat: { label: "True Shooting %", value: "62.1%", trend: "Top 4% efficiency" },
    athletesTracked: "11,200+",
  },
  {
    id: "volleyball",
    name: "Volleyball",
    category: "team",
    subcategory: "Court Team Sport",
    href: "/sports/relay",
    description: "Spike jump peak height, kill percentage, setter distribution heatmaps, dig conversion rate, and rotational transition speed.",
    iconName: "TrendingUp",
    metrics: ["Vertical Spike Height", "Hitting %", "Service Ace Ratio", "Dig Conversion", "Side-Out Efficiency"],
    primaryStat: { label: "Kill Efficiency", value: "48.2%", trend: "3.28m spike reach" },
    athletesTracked: "4,820+",
  },
  {
    id: "rugby",
    name: "Rugby / American Football",
    category: "team",
    subcategory: "Collision Team Sport",
    href: "/sports/football",
    description: "Tackle completion %, scrum torque impact, route separation distance, EPA (Expected Points Added), and sprint deceleration.",
    iconName: "Shield",
    metrics: ["Tackle Completion", "EPA / Play", "Meters Gained Post-Contact", "Sprint Workload (km)", "Turnover Differential"],
    primaryStat: { label: "EPA / Play", value: "+0.18", trend: "89% tackle efficiency" },
    athletesTracked: "6,940+",
  },
  {
    id: "cricket",
    name: "Cricket",
    category: "team",
    subcategory: "Bat & Ball",
    href: "/sports/football",
    description: "Bowling release trajectory, pitch seam & swing angle (degrees), wagon wheel shot analysis, and run-rate predictive modeling.",
    iconName: "Target",
    metrics: ["Bowling Speed (km/h)", "Swing / Seam Angle", "Dot Ball %", "Wagon Wheel Placement", "Expected Wickets (xW)"],
    primaryStat: { label: "Bowling Speed", value: "144.2 km/h", trend: "1.8° late outswing" },
    athletesTracked: "5,890+",
  },
];

export const GAME_ANALYSIS_MODULES = [
  {
    id: "match-dashboard",
    name: "Match Dashboard",
    category: "analysis" as const,
    href: "/sports/game-analysis",
    description: "Real-time game clock tracking, live score events, momentum shifts, pitch control, and instantaneous win probability curves.",
    iconName: "LayoutDashboard",
    stat: "Sub-second live stream feeds",
  },
  {
    id: "tactical-insights",
    name: "Tactical Insights",
    category: "analysis" as const,
    href: "/sports/game-analysis",
    description: "AI formation detection, high-press vulnerability flags, spacing anomalies, and counter-attack phase decomposition.",
    iconName: "BrainCircuit",
    stat: "Over 85 tactical event triggers",
  },
  {
    id: "player-comparison",
    name: "Player Comparison",
    category: "analysis" as const,
    href: "/sports/game-analysis",
    description: "Head-to-head radar charts, speed and endurance percentiles, positional benchmarks, and direct matchup histories.",
    iconName: "Users",
    stat: "12-axis performance spider charts",
  },
  {
    id: "team-comparison",
    name: "Team Comparison",
    category: "analysis" as const,
    href: "/sports/game-analysis",
    description: "Roster aggregate stamina, bench depth evaluation, head-to-head style match ups, and set-piece efficiency ratings.",
    iconName: "BarChart3",
    stat: "Aggregate team chemistry & pace",
  },
  {
    id: "event-detection",
    name: "Event Detection",
    category: "analysis" as const,
    href: "/sports/game-analysis",
    description: "Automated video and sensor timestamping for shots, turnovers, tackles, offside lines, and substitution impacts.",
    iconName: "Video",
    stat: "99.2% automated tagging precision",
  },
  {
    id: "custom-reports",
    name: "Custom Reports",
    category: "analysis" as const,
    href: "/sports/game-analysis",
    description: "One-click PDF/presentation export for coaching staff, post-match debrief sheets, and tailored athlete feedback summaries.",
    iconName: "FileSpreadsheet",
    stat: "Export ready in under 3 seconds",
  },
];
