/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AthletePerformanceRouteImport } from './routes/athlete-performance'
import { Route as AthletesRouteImport } from './routes/athletes'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CoachesRouteImport } from './routes/coaches'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as HelpRouteImport } from './routes/help'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RunAnalyticsRouteImport } from './routes/run-analytics'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SportsIndexRouteImport } from './routes/sports.index'
import { Route as SportsFootballRouteImport } from './routes/sports.football'
import { Route as SportsGameAnalysisRouteImport } from './routes/sports.game-analysis'
import { Route as SportsHockeyRouteImport } from './routes/sports.hockey'
import { Route as SportsRelayRouteImport } from './routes/sports.relay'
import { Route as SportsRunningRouteImport } from './routes/sports.running'
import { Route as SportsSwimmingRouteImport } from './routes/sports.swimming'
import { Route as SportsAthleticsHighJumpRouteImport } from './routes/sports.athletics.high-jump'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AthletePerformanceRoute = AthletePerformanceRouteImport.update({
  id: '/athlete-performance',
  path: '/athlete-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const AthletesRoute = AthletesRouteImport.update({
  id: '/athletes',
  path: '/athletes',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesRoute = CoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RunAnalyticsRoute = RunAnalyticsRouteImport.update({
  id: '/run-analytics',
  path: '/run-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsIndexRoute = SportsIndexRouteImport.update({
  id: '/sports/',
  path: '/sports/',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsFootballRoute = SportsFootballRouteImport.update({
  id: '/sports/football',
  path: '/sports/football',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsGameAnalysisRoute = SportsGameAnalysisRouteImport.update({
  id: '/sports/game-analysis',
  path: '/sports/game-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsHockeyRoute = SportsHockeyRouteImport.update({
  id: '/sports/hockey',
  path: '/sports/hockey',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRelayRoute = SportsRelayRouteImport.update({
  id: '/sports/relay',
  path: '/sports/relay',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRunningRoute = SportsRunningRouteImport.update({
  id: '/sports/running',
  path: '/sports/running',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsSwimmingRoute = SportsSwimmingRouteImport.update({
  id: '/sports/swimming',
  path: '/sports/swimming',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsAthleticsHighJumpRoute = SportsAthleticsHighJumpRouteImport.update({
  id: '/sports/athletics/high-jump',
  path: '/sports/athletics/high-jump',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/athlete-performance': typeof AthletePerformanceRoute
  '/athletes': typeof AthletesRoute
  '/careers': typeof CareersRoute
  '/coaches': typeof CoachesRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/ecosystem': typeof EcosystemRoute
  '/help': typeof HelpRoute
  '/insights': typeof InsightsRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/recommendations': typeof RecommendationsRoute
  '/resources': typeof ResourcesRoute
  '/run-analytics': typeof RunAnalyticsRoute
  '/terms': typeof TermsRoute
  '/sports/football': typeof SportsFootballRoute
  '/sports/game-analysis': typeof SportsGameAnalysisRoute
  '/sports/hockey': typeof SportsHockeyRoute
  '/sports/relay': typeof SportsRelayRoute
  '/sports/running': typeof SportsRunningRoute
  '/sports/swimming': typeof SportsSwimmingRoute
  '/sports/': typeof SportsIndexRoute
  '/sports/athletics/high-jump': typeof SportsAthleticsHighJumpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/athlete-performance': typeof AthletePerformanceRoute
  '/athletes': typeof AthletesRoute
  '/careers': typeof CareersRoute
  '/coaches': typeof CoachesRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/ecosystem': typeof EcosystemRoute
  '/help': typeof HelpRoute
  '/insights': typeof InsightsRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/recommendations': typeof RecommendationsRoute
  '/resources': typeof ResourcesRoute
  '/run-analytics': typeof RunAnalyticsRoute
  '/terms': typeof TermsRoute
  '/sports/football': typeof SportsFootballRoute
  '/sports/game-analysis': typeof SportsGameAnalysisRoute
  '/sports/hockey': typeof SportsHockeyRoute
  '/sports/relay': typeof SportsRelayRoute
  '/sports/running': typeof SportsRunningRoute
  '/sports/swimming': typeof SportsSwimmingRoute
  '/sports': typeof SportsIndexRoute
  '/sports/athletics/high-jump': typeof SportsAthleticsHighJumpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/athlete-performance': typeof AthletePerformanceRoute
  '/athletes': typeof AthletesRoute
  '/careers': typeof CareersRoute
  '/coaches': typeof CoachesRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/ecosystem': typeof EcosystemRoute
  '/help': typeof HelpRoute
  '/insights': typeof InsightsRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/recommendations': typeof RecommendationsRoute
  '/resources': typeof ResourcesRoute
  '/run-analytics': typeof RunAnalyticsRoute
  '/terms': typeof TermsRoute
  '/sports/football': typeof SportsFootballRoute
  '/sports/game-analysis': typeof SportsGameAnalysisRoute
  '/sports/hockey': typeof SportsHockeyRoute
  '/sports/relay': typeof SportsRelayRoute
  '/sports/running': typeof SportsRunningRoute
  '/sports/swimming': typeof SportsSwimmingRoute
  '/sports/': typeof SportsIndexRoute
  '/sports/athletics/high-jump': typeof SportsAthleticsHighJumpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analytics'
    | '/athlete-performance'
    | '/athletes'
    | '/careers'
    | '/coaches'
    | '/community'
    | '/contact'
    | '/dashboard'
    | '/ecosystem'
    | '/help'
    | '/insights'
    | '/platform'
    | '/pricing'
    | '/privacy'
    | '/recommendations'
    | '/resources'
    | '/run-analytics'
    | '/terms'
    | '/sports/football'
    | '/sports/game-analysis'
    | '/sports/hockey'
    | '/sports/relay'
    | '/sports/running'
    | '/sports/swimming'
    | '/sports/'
    | '/sports/athletics/high-jump'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analytics'
    | '/athlete-performance'
    | '/athletes'
    | '/careers'
    | '/coaches'
    | '/community'
    | '/contact'
    | '/dashboard'
    | '/ecosystem'
    | '/help'
    | '/insights'
    | '/platform'
    | '/pricing'
    | '/privacy'
    | '/recommendations'
    | '/resources'
    | '/run-analytics'
    | '/terms'
    | '/sports/football'
    | '/sports/game-analysis'
    | '/sports/hockey'
    | '/sports/relay'
    | '/sports/running'
    | '/sports/swimming'
    | '/sports'
    | '/sports/athletics/high-jump'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analytics'
    | '/athlete-performance'
    | '/athletes'
    | '/careers'
    | '/coaches'
    | '/community'
    | '/contact'
    | '/dashboard'
    | '/ecosystem'
    | '/help'
    | '/insights'
    | '/platform'
    | '/pricing'
    | '/privacy'
    | '/recommendations'
    | '/resources'
    | '/run-analytics'
    | '/terms'
    | '/sports/football'
    | '/sports/game-analysis'
    | '/sports/hockey'
    | '/sports/relay'
    | '/sports/running'
    | '/sports/swimming'
    | '/sports/'
    | '/sports/athletics/high-jump'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AthletePerformanceRoute: typeof AthletePerformanceRoute
  AthletesRoute: typeof AthletesRoute
  CareersRoute: typeof CareersRoute
  CoachesRoute: typeof CoachesRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  EcosystemRoute: typeof EcosystemRoute
  HelpRoute: typeof HelpRoute
  InsightsRoute: typeof InsightsRoute
  PlatformRoute: typeof PlatformRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RecommendationsRoute: typeof RecommendationsRoute
  ResourcesRoute: typeof ResourcesRoute
  RunAnalyticsRoute: typeof RunAnalyticsRoute
  TermsRoute: typeof TermsRoute
  SportsFootballRoute: typeof SportsFootballRoute
  SportsGameAnalysisRoute: typeof SportsGameAnalysisRoute
  SportsHockeyRoute: typeof SportsHockeyRoute
  SportsRelayRoute: typeof SportsRelayRoute
  SportsRunningRoute: typeof SportsRunningRoute
  SportsSwimmingRoute: typeof SportsSwimmingRoute
  SportsIndexRoute: typeof SportsIndexRoute
  SportsAthleticsHighJumpRoute: typeof SportsAthleticsHighJumpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete-performance': {
      id: '/athlete-performance'
      path: '/athlete-performance'
      fullPath: '/athlete-performance'
      preLoaderRoute: typeof AthletePerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athletes': {
      id: '/athletes'
      path: '/athletes'
      fullPath: '/athletes'
      preLoaderRoute: typeof AthletesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches': {
      id: '/coaches'
      path: '/coaches'
      fullPath: '/coaches'
      preLoaderRoute: typeof CoachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run-analytics': {
      id: '/run-analytics'
      path: '/run-analytics'
      fullPath: '/run-analytics'
      preLoaderRoute: typeof RunAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/': {
      id: '/sports/'
      path: '/sports'
      fullPath: '/sports/'
      preLoaderRoute: typeof SportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/football': {
      id: '/sports/football'
      path: '/sports/football'
      fullPath: '/sports/football'
      preLoaderRoute: typeof SportsFootballRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/game-analysis': {
      id: '/sports/game-analysis'
      path: '/sports/game-analysis'
      fullPath: '/sports/game-analysis'
      preLoaderRoute: typeof SportsGameAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/hockey': {
      id: '/sports/hockey'
      path: '/sports/hockey'
      fullPath: '/sports/hockey'
      preLoaderRoute: typeof SportsHockeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/relay': {
      id: '/sports/relay'
      path: '/sports/relay'
      fullPath: '/sports/relay'
      preLoaderRoute: typeof SportsRelayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/running': {
      id: '/sports/running'
      path: '/sports/running'
      fullPath: '/sports/running'
      preLoaderRoute: typeof SportsRunningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/swimming': {
      id: '/sports/swimming'
      path: '/sports/swimming'
      fullPath: '/sports/swimming'
      preLoaderRoute: typeof SportsSwimmingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/athletics/high-jump': {
      id: '/sports/athletics/high-jump'
      path: '/sports/athletics/high-jump'
      fullPath: '/sports/athletics/high-jump'
      preLoaderRoute: typeof SportsAthleticsHighJumpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalyticsRoute: AnalyticsRoute,
  AthletePerformanceRoute: AthletePerformanceRoute,
  AthletesRoute: AthletesRoute,
  CareersRoute: CareersRoute,
  CoachesRoute: CoachesRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  EcosystemRoute: EcosystemRoute,
  HelpRoute: HelpRoute,
  InsightsRoute: InsightsRoute,
  PlatformRoute: PlatformRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RecommendationsRoute: RecommendationsRoute,
  ResourcesRoute: ResourcesRoute,
  RunAnalyticsRoute: RunAnalyticsRoute,
  TermsRoute: TermsRoute,
  SportsFootballRoute: SportsFootballRoute,
  SportsGameAnalysisRoute: SportsGameAnalysisRoute,
  SportsHockeyRoute: SportsHockeyRoute,
  SportsRelayRoute: SportsRelayRoute,
  SportsRunningRoute: SportsRunningRoute,
  SportsSwimmingRoute: SportsSwimmingRoute,
  SportsIndexRoute: SportsIndexRoute,
  SportsAthleticsHighJumpRoute: SportsAthleticsHighJumpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
