import type { ReactNode } from "react";
import { ArrowUpRight, Info, Sparkles, TrendingUp } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { cn } from "@/lib/utils";

export function DemoBadge() { return <span className="inline-flex items-center gap-1.5 rounded-full border border-primary/25 bg-primary/10 px-2.5 py-1 text-[11px] font-semibold uppercase tracking-widest text-primary"><span className="h-1.5 w-1.5 rounded-full bg-primary" />Demo data</span>; }
export function Eyebrow({ children }: { children: ReactNode }) { return <div className="mb-4 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.16em] text-primary"><span className="h-px w-7 bg-primary" />{children}</div>; }
export function PageIntro({ eyebrow, title, text, action }: { eyebrow: string; title: string; text: string; action?: ReactNode }) { return <section className="page-intro"><div className="content-wrap grid gap-7 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-end"><div className="max-w-3xl"><Eyebrow>{eyebrow}</Eyebrow><h1 className="text-balance text-4xl font-semibold leading-[1.05] text-foreground sm:text-5xl lg:text-6xl">{title}</h1><p className="mt-5 max-w-2xl text-base leading-7 text-muted-foreground sm:text-lg">{text}</p></div>{action}</div></section>; }
export function SectionHead({ eyebrow, title, text, action }: { eyebrow?: string; title: string; text?: string; action?: ReactNode }) { return <div className="mb-8 grid grid-cols-[minmax(0,1fr)_auto] items-end gap-5"><div className="min-w-0">{eyebrow && <Eyebrow>{eyebrow}</Eyebrow>}<h2 className="text-balance text-2xl font-semibold sm:text-3xl">{title}</h2>{text && <p className="mt-3 max-w-2xl leading-7 text-muted-foreground">{text}</p>}</div>{action}</div>; }
export function MetricCard({ label, value, note, icon }: { label: string; value: string; note?: string; icon?: ReactNode }) { return <article className="metric-card"><div className="flex items-start justify-between gap-3"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-muted-foreground">{label}</p><span className="text-primary">{icon ?? <TrendingUp className="h-4 w-4" />}</span></div><p className="mt-5 text-3xl font-semibold tabular-nums text-foreground">{value}</p>{note && <p className="mt-2 text-xs text-muted-foreground">{note}</p>}</article>; }
const tooltipStyle = { backgroundColor: "var(--popover)", border: "1px solid var(--border)", borderRadius: "8px", color: "var(--popover-foreground)", fontSize: "12px", boxShadow: "0 10px 25px -5px rgba(15, 23, 42, 0.1)" };
export function LineChartCard({ title, subtitle, data, keys = ["performance"], unit = "" }: { title: string; subtitle?: string; data: Array<Record<string, string | number>>; keys?: string[]; unit?: string }) { return <article className="chart-card"><div className="mb-6"><h3 className="font-semibold">{title}</h3>{subtitle && <p className="mt-1 text-xs text-muted-foreground">{subtitle}</p>}</div><div className="h-64 w-full"><ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{ top: 8, right: 8, left: -22, bottom: 0 }}><CartesianGrid stroke="var(--border)" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="label" stroke="var(--muted-foreground)" tickLine={false} axisLine={false}/><YAxis stroke="var(--muted-foreground)" tickLine={false} axisLine={false}/><Tooltip contentStyle={tooltipStyle} formatter={(value) => [`${value}${unit}`, ""]}/>{keys.map((key, i) => <Line key={key} type="monotone" dataKey={key} stroke={i === 0 ? "var(--primary)" : "var(--chart-2)"} strokeWidth={2.5} dot={false} activeDot={{ r: 5 }} />)}</LineChart></ResponsiveContainer></div></article>; }
export function BarChartCard({ title, subtitle, data, dataKey = "distance" }: { title: string; subtitle?: string; data: Array<Record<string, string | number>>; dataKey?: string }) { return <article className="chart-card"><div className="mb-6"><h3 className="font-semibold">{title}</h3>{subtitle && <p className="mt-1 text-xs text-muted-foreground">{subtitle}</p>}</div><div className="h-64 w-full"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} margin={{ top: 8, right: 8, left: -22, bottom: 0 }}><CartesianGrid stroke="var(--border)" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="label" stroke="var(--muted-foreground)" tickLine={false} axisLine={false}/><YAxis stroke="var(--muted-foreground)" tickLine={false} axisLine={false}/><Tooltip contentStyle={tooltipStyle}/><Bar dataKey={dataKey} fill="var(--primary)" radius={[3,3,0,0]} /></BarChart></ResponsiveContainer></div></article>; }
export function AreaChartCard({ title, data }: { title: string; data: Array<Record<string, string | number>> }) { return <article className="chart-card"><h3 className="mb-6 font-semibold">{title}</h3><div className="h-64"><ResponsiveContainer><AreaChart data={data} margin={{ top: 8, right: 8, left: -22, bottom: 0 }}><defs><linearGradient id="areaFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--primary)" stopOpacity={0.35}/><stop offset="100%" stopColor="var(--primary)" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="var(--border)" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="label" stroke="var(--muted-foreground)" tickLine={false} axisLine={false}/><YAxis stroke="var(--muted-foreground)" tickLine={false} axisLine={false}/><Tooltip contentStyle={tooltipStyle}/><Area type="monotone" dataKey="performance" stroke="var(--primary)" fill="url(#areaFill)" strokeWidth={2.5}/></AreaChart></ResponsiveContainer></div></article>; }
export function InsightCard({ type, title, detail, metric, className }: { type: string; title: string; detail: string; metric?: string; className?: string }) { return <article className={cn("group surface-card p-5 transition hover:border-primary/35", className)}><div className="flex items-center justify-between gap-4"><span className="text-[11px] font-bold uppercase tracking-[0.14em] text-primary">{type}</span>{metric && <span className="font-mono text-sm text-foreground">{metric}</span>}</div><h3 className="mt-4 text-lg font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{detail}</p><div className="mt-5 flex items-center gap-2 text-xs font-semibold text-foreground"><Sparkles className="h-3.5 w-3.5 text-primary" />Generated from performance signals</div></article>; }
export function Workflow({ title, steps, description }: { title: string; steps: string[]; description: string }) { return <article className="surface-card overflow-hidden"><div className="border-b border-border p-6"><p className="text-xs font-bold uppercase tracking-[0.14em] text-primary">Automation flow</p><h3 className="mt-2 text-xl font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{description}</p></div><div className="grid gap-0 p-4 sm:grid-cols-3 lg:grid-cols-6">{steps.map((step, index) => <div key={step} className="relative flex min-h-24 items-center gap-3 border-b border-border p-3 last:border-0 sm:border-b-0 sm:border-r sm:last:border-r-0"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-md bg-primary/10 font-mono text-xs font-bold text-primary">{String(index + 1).padStart(2,"0")}</span><span className="text-sm font-medium">{step}</span>{index < steps.length - 1 && <ArrowUpRight className="absolute right-1 top-2 h-3.5 w-3.5 text-muted-foreground" />}</div>)}</div></article>; }
export function DemoNotice({ children = "Analytics-based demo guidance. Not medical advice." }: { children?: ReactNode }) { return <div className="flex items-start gap-3 rounded-md border border-accent/30 bg-accent/10 p-4 text-sm text-muted-foreground"><Info className="mt-0.5 h-4 w-4 shrink-0 text-accent" /><span>{children}</span></div>; }
export function Segmented({ values, value, onChange }: { values: string[]; value: string; onChange: (value: string) => void }) { return <div className="inline-flex rounded-md border border-border bg-secondary p-1" role="group" aria-label="Time period">{values.map((item) => <button key={item} onClick={() => onChange(item)} className={cn("rounded px-3 py-1.5 text-xs font-semibold transition", value === item ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:text-foreground")}>{item}</button>)}</div>; }
